# -*- coding: utf-8 -*-
{
        'name':'Employee Evaluation & Rating System',
        'category':'Human Resources',
        'version':'1.0',
        'website': 'http://ktree.com/',
        'author':'KTree Computer Solutions India (P) Ltd',
	'summary': 'Employee Evaluation, Attendances, Reporting, Configurations',
        'description':""" It is to evaluate employee performance through rating provided by supervisor/manager of their respective department. Based upon the average rating score of a particular year the salary increment will be calculated. """,
        'depends':[
		   'base',
		   'hr',
		   'hr_attendance',
		   'decimal_precision',
           'sg_holiday_extended',
	],
        'images': ['images/main-screenshot.png'],
        'data':[
                'security/res_groups.xml',
                'views/education_qual_view.xml',
                'views/employee_view.xml',
                'views/employee_memo_view.xml',
                'views/year_config_view.xml',
                'views/rating_config_view.xml',
                'views/hr_department_view.xml',
                'views/salary_band_view.xml',
                'views/employee_evaluation_view.xml',
                'views/sequence_view.xml',
                'views/hr_attendance_view.xml',
                'views/res_config_view.xml',
                'views/attendance_percentage_view.xml',
                'wizard/import_success_view.xml',
                'wizard/salary_history_view.xml',
                'wizard/evaluation_report_view.xml',
                'wizard/performance_report_view.xml',
                'wizard/salary_report_view.xml',
                'wizard/emp_memo_history_view.xml',
                'wizard/import_attendance_view.xml',
                'wizard/import_employee_evaluation_view.xml',
                'report/report_salaryhistory_view.xml',
                'report/report_memohistory_view.xml',
                'report/report_employee_evaluation_view.xml',
                'report/report.xml',
                'report/report_employee_salary_view.xml',
                'security/ir_rule.xml',
                'security/ir.model.access.csv', 
                'views/menus_order_view.xml',
                 
         ],
#         'demo':['demo/demo_data.xml'],
        'installable':True,
        'auto_install':False,
        'application':True,
        'price':35.00, 
        'currency':'EUR',
        'license':'AGPL-3'
}

