# -*- coding: utf-8 -*-
# See LICENSE file for full copyright and licensing details.

{
    'name': 'Fees Management',
    'version': "10.0.1.0.4",
    'author': 'HashMicro / Ajay / Bhavik - TechnoSquare',
    'website': 'http://www.serpentcs.com',
    'images': ['static/description/SchoolFees.png'],
    'category': 'School Management',
    'license': "AGPL-3",
    'complexity': 'easy',
    'summary': 'A Module For Fees Management In School',
    'depends': ['account', 'account', 'atts_course','atts_student_fields', 'theme_atts'],
    'data': ['security/ir.model.access.csv',
             'security/security_fees.xml',
             'views/school_fees_view.xml',
             'views/school_fees_sequence.xml',
             'views/student_payslip.xml',
             'views/student_fees_register.xml',
             'views/fee_invoice_view.xml',
             # 'views/report_view.xml',
             'views/fee_receipt.xml',
             'views/outstanding_fee_report.xml',
             'views/billing_report.xml',
             'views/billing_report_letter.xml',
             'views/billing_reminder.xml',
             'wizard/fee_receipt_wizard.xml',
             'wizard/outstanding_fee_report_wizard.xml',
             'views/registration_fee.xml',
             'report/report_joining _information.xml',
             'report/report_fee_invoice.xml',
             'report/report_credit_note.xml',
             'data/mail_template_data.xml',
             'data/ir_sequence_data.xml',
             ],
    'demo': [],
    'installable': True,
    'application': True
}
