# -*- coding: utf-8 -*-
{
    'name': 'Helaspice Receiving Import',
    'version': '1.0',
    'category': 'Import',
    'sequence': 10,
    'summary': 'Import',
    'website': 'http://www.hashmicro.com/',
    'author': 'Hashmicro/ GBS TechnoSoft',
    'depends': ['product_expiry', 'hm_std_inventory', 'warehouse_serializer'],
    'data': [
        'security/ir.model.access.csv',
        'data/mail_template_data.xml',
        'views/hide_menu.xml',
        'views/product_view.xml',
        'views/stock_view.xml',
        'views/stock_count_view.xml',
        'views/stock_production_lot_view.xml',
        'views/manage_incoming_batch.xml',
        'views/stock_inventory_view.xml',
        'wizard/import_po_wizard.xml',
        'wizard/repacking_wizard.xml',
        'wizard/discrepancy_report_view.xml',
        'report/repacking_label.xml',
        'report/report_repacking.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}