{
    'name': 'Hashmicro Fields',
    'description': 'This module will add fields in CRM.',
    'category': 'CRM',
    'version': '1.0',
    'author': 'HashMicro / Mustufa Kantawala / MP Technolabs',
    'website': 'www.hashmicro.com',
    'depends': ['crm', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'wizard/crm_lead_lost_views.xml',
        'wizard/crm_activity_log_views.xml',
        'views/calendar_views.xml',
        'views/crm_lead.xml',
        'views/crm_reseller.xml',
        'security/ir_security.xml',
    ],
    'application': True,
    'installable': True,
}