# -*- coding: utf-8 -*-
{
    'name' : 'Aikchin Modifier Fields',
    'version' : '1.0',
    'category': 'Account',
    'author': 'HashMicro / MP technolabs / Monali / Bipin Prajapati',
    'description': """Modify the menu and sub-menu name for Accounting module.
    """,
    'website': 'www.hashmicro.com',
    'depends' : [
        'account',
        'account_voucher',
        'point_of_sale',
        'account_asset',
        'sg_bank_reconcile',
        'sale',
        'l10n_sg_hr_payroll',
        'stock',
        'sale_stock',
        'multiple_customer_delivery_address',
        'sale_discount_total',
	    'sg_account_standardisation',
        'expense_masking',
        'employee_appraisal',
    ],
    'data': [
	    'security/security_view.xml',
	    'views/menu.xml',
	    'views/account_report.xml',
	    'views/template.xml',
	    'views/account_invoice_view.xml',
	    'views/sale_order_view.xml',
	    'views/sale_report.xml',
        'views/res_partner_view.xml',
        'views/product_product.xml',
        'views/purchase_view.xml',
        'views/account_report_menu.xml',
        'views/human_resources_view.xml',
        'views/hr_holidays_view.xml',
    ],
    'demo': [
    ],
    'qweb': ['static/src/xml/pos.xml'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
